version: '3.9'
services:

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=1y'
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  prometheus-pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    restart: always

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana

  data-collector:
    build: data-collector
    restart: always
    depends_on:
      - prometheus-pushgateway

volumes:
  grafana-data:
  prometheus-data:

